### ISSUE TITLE
Support Heartbeat Monitoring

### ISSUE THREAD

**Issue by tannertechnology** [playit-cloud/playit-agent#15]
Hey,

I plan to implement a confiugrable option that enables simple heartbeat monitoring by sending a get or post request to a certain url with no data at a configured interval. I plan to use it with BetterUptime but it would work with any cron/heartbeat monitoring service.

**Comment by loriopatrick** [comment]
Oh interesting, so like a HTTP healthcheck endpoint? I'm currently working on a refactor where all the core logic is broken into it's own module. This would be really cool feature for a daemon version of playit.

**Comment by tannertechnology** [comment]
Hey Patrick,

At work I use a service called betteruptime which lets you just curl a URL to indicate the service is alive, and you configure how long it should wait before alerting. My thought was if it could run every 5 minutes it would at least alert me when the playit agent (rather than just the service behind it) goes offline.

**Comment by loriopatrick** [comment]
Seems reasonable to use with thirdparty services. Best for monitoring services to be separate from the service they're monitoring because if playit is having issues it might not be able to report that it's having issues because it's having issues.
