### ISSUE TITLE
Please release i386 (32-bit) deb package

### ISSUE THREAD

**Issue by albertdb** [playit-cloud/playit-agent#23]
Could you please provide 32-bit compilations?

Thanks

**Comment by tannertechnology** [comment]
32 bit windows build also requested here: https://discuss.playit.gg/t/not-running-on-32-bit-windows/940

I'll have a look

**Comment by tannertechnology** [comment]
For linux the 32 bit build is already in the github action, the windows build is a bit more complex: https://github.com/tannertechnology/playit-agent/actions/runs/3353384625/jobs/5556118179

The file output needs to be tidied as well, I'll do some more on this later.

**Comment by TheBotlyNoob** [comment]
this should be covered by #37.

**Comment by loriopatrick** [comment]
we now build 32bit for Windows, I can look into adding 32bit target for linux

**Comment by loriopatrick** [comment]
32bit support added
