### ISSUE TITLE
Support for running Playit as a daemon that can run independently from TUI

### ISSUE THREAD

**Issue by nicholasgrose** [playit-cloud/playit-agent#24]
Presently Playit's TUI is bound to the agent actually running. It would be nice if the TUI could run independently from the agent, so that the TUI can be opened and closed without affecting whether the agent is actually running.

**Comment by loriopatrick** [comment]
That's an interesting idea. I'm currently working on a large refactor where the core playit logic is going to broken into its own module. I probably won't have time to do this request but it should be much easier to do soon if you're interested in tackling.

**Comment by obj-obj** [comment]
You can already do something similar to this using GNU Screen and a systemd service:
```
[Unit]
Description=Playit
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/bin/screen -DmS playit playit

[Install]
WantedBy=default.target
```

And view the TUI at any time using `screen -x playit`

**Comment by nicholasgrose** [comment]
> You can already do something similar to this using GNU Screen and a systemd service:
> ```
> [Unit]
> Description=Playit
> After=network-online.target
> Wants=network-online.target
> 
> [Service]
> Type=simple
> ExecStart=/bin/screen -DmS playit playit
> 
> [Install]
> WantedBy=default.target
> ```
> 
> And view the TUI at any time using `screen -x playit`

I may need to use using your solution (or something similar via tmux) in the meantime, then! Especially since I can specify the user in systemd, too, so that it doesn't run as root.

I may eventually try my hand at implementing this feature at a later date, but my own time constraints have prevented me up to this point. It's nice to have, but workarounds like this work for now.

**Comment by obj-obj** [comment]
> > You can already do something similar to this using GNU Screen and a systemd service:
> > ```
> > [Unit]
> > Description=Playit
> > After=network-online.target
> > Wants=network-online.target
> > 
> > [Service]
> > Type=simple
> > ExecStart=/bin/screen -DmS playit playit
> > 
> > [Install]
> > WantedBy=default.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And view the TUI at any time using `screen -x playit`
> 
> I may need to use using your solution (or something similar via tmux) in the meantime, then! Especially since I can specify the user in systemd, too, so that it doesn't run as root.
> 
> I may eventually try my hand at implementing this feature at a later date, but my own time constraints have prevented me up to this point. It's nice to have, but workarounds like this work for now.

@nicholasgrose I just run this as a user service (`~/.config/systemd/user/playit.service`) so it doesn't run as root

**Comment by loriopatrick** [comment]
systemd service is now installed with our debian package :)
