### ISSUE TITLE
agent_common need serde_json as dependencies explicitly

### ISSUE THREAD

**Issue by afm0901x** [playit-cloud/playit-agent#29]
Build failed with error:

> error[E0433]: failed to resolve: use of undeclared crate or module \`serde_json\`

https://github.com/playit-cloud/playit-agent/blob/6273120f04b5005b9043a7d0e705990e7c75485b/packages/agent_common/src/rpc.rs#L175
https://github.com/playit-cloud/playit-agent/blob/6273120f04b5005b9043a7d0e705990e7c75485b/packages/agent_common/src/rpc.rs#L176

this merge https://github.com/playit-cloud/playit-agent/pull/28 supposed to fix it,
but this happen again in latest commit.

**Comment by loriopatrick** [comment]
Added serde_json as a dev dependency
