### ISSUE TITLE
Please Fix Iranian Bad Ping

### ISSUE THREAD

**Issue by Ghalbeyou** [playit-cloud/playit-agent#31]
Hello,
please add server in iran. we have really bad ping because we're in iran.

**Comment by Ghalbeyou** [comment]
Hey,
Please Fix This bad PING in iran. add server in iran idk, anything that can fix this ping

**Comment by tannertechnology** [comment]
Hey Ghalbeyou, please ask this in the official Discord. This repository is for code issues with the agent itself. Thanks! 

https://discord.gg/AXAbujx
