### ISSUE TITLE
Duplicate connections on Lubuntu 22.04

### ISSUE THREAD

**Issue by bennasar99** [playit-cloud/playit-agent#34]
When running the agent on Linux (Lubuntu 22.04), connection duplication / triplication issues and frequent disconnection.

However, on the same computer and the same network, when running the agent on Windows, I get none of this issues.

Running latest version, 0.9.3

**Comment by loriopatrick** [comment]
I don't know what "connection duplication / triplication issues" means. Could you explain a bit more?

**Comment by bennasar99** [comment]
When I start the agent "Overview" shows "TCP Client Count; 0", as expected.
But when I connect (ssh, password screen) "TCP Client Count" is set to 1. When I enter my password, it jumps to 2. It can even jump to 3 a few seconds later.
Later (before a minute), the number of TCP Clients starts to drop until it gets to 0 again, and my session (which is really only 1) is disconnected ("Remote side unexpectedly closed network connection" in ssh, "Disconnected from server" in minecraft).
Meanwhile in "Tunnels" I can see "Connections: 0" while on Windows it shows my connections correctly. Also, on windows "TCP Client Count" is always 1.

**Comment by bennasar99** [comment]
Maybe it has something to do with this issue? [https://github.com/playit-cloud/playit-agent/commit/2c32794acf17eb76b0c4a1d7d7b4da6e2d7dd32c](url)

**Comment by loriopatrick** [comment]
No that's different, that prevents handing duplicate SYN packets. Not sure what's happening in your case. I recommend running ssh with verbose logging `-vv`.

**Comment by bennasar99** [comment]
I get the following when the connection drops (taken from ssh with verbose):
```
lhrdebug3: send packet: type 1
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i0/0 o0/0 e[write]/0 fd 4/5/6 sock -1 cc -1 io 0x01/0x00)

Connection to when-citizenship.at.ply.gg closed by remote host.
Connection to when-citizenship.at.ply.gg closed.
Transferred: sent 2860, received 2864 bytes, in 166.8 seconds
Bytes per second: sent 17.1, received 17.2
debug1: Exit status -1
```

**Comment by bennasar99** [comment]
Also, I get this in playit logs:
```
ERROR tcp                                        
client{tunnel_address=209.25.141.2:43783 local_address=127.0.0.1:22}:local to
tunnel: playit_agent_core::tcp_client: connection timed out                  
2022-10-04T18:58:27.167395Z ERROR tcp                                        
client{tunnel_address=209.25.141.2:43783 local_address=127.0.0.1:22}:tunnel  
to local: playit_agent_core::tcp_client: connection timed out
```

**Comment by loriopatrick** [comment]
A lot has changed since this issue was opened. Hopefully resolved, if not please create a new issue.
