### ISSUE TITLE
Nodejs Package integration

### ISSUE THREAD

**Issue by Sirherobrine23** [playit-cloud/playit-agent#36]
I'm creating a package in NodeJS to manage several Minecraft servers and in this package I'm integrating playit to facilitate the creation of the tunnel, I don't understand much about rust but I've already done some functions, this is the main function: [Bds Maneger Core /src/utils/proxy.ts](https://github.com/The-Bds-Maneger/Bds-Maneger-Core/blob/17c39e4c632e01132a3f725137d5b1013b4baf8e/src/utils/proxy.ts#L96-L150), later I will export to a module separate from the Bds Maneger core.

now i'm stuck on creating a tunnel and agents

**Comment by maxomatic458** [comment]
Not really an answer to your question, but the plan is to standardize the api and make playit easy to integrate in other applications.

Copied from the playit.gg discord:

<:playitcomputer:1009595911015514163> **Development Update** <:playitcomputer:1009595911015514163> 

<@&951918368234016818> 

Over the next few weeks I'm going to be working to standardize the Playit API and redesign the website. The goal is to standardize around the "playit agent" concept. The "playit agent" is something that runs on your computer and has "tunnels". With the open API and standardization, the hope is that third parties can create their own tailor made "playit agents". "playit agents" could be in game mods, linux packages, embedded in programs. Basically we're looking to make it really easy for developers to use playit so people can self host their own public servers. We're still going to make our own playit agents with mods and stand alone programs but soon many more will be able to also.

These updates are also going to set the path on how playit make money. Right now we have two products:
1) Custom domain for $1/month or $6/year
2) Dedicated IPs for $10/month or $100/year

In the future the plan is to have `playit free` and `playit premium`. Everything that is free now will remain free and be in the `playit free` plan. `playit premium` will be $3/month and include more tunnels, more playit agents, more firewalls, more ..., custom domains, and new features. People that want even more will be able to add that to their subscription on a per unit basis. All the pricing details haven't been figure out yet and I'll more to share closer to release.

A lot of work will be happening in the background so there probably won't be too many visible updates for awhile. I'll try and share updates and screenshots here as process is made :).

**Comment by Sirherobrine23** [comment]
Estou feliz que o projeto esteja evoluindo, comecei a usar recentemente, e me ajudou muito com a implemetaçao do uso dos containers remotamente onde não consigo expor as portas.

**Comment by Sirherobrine23** [comment]
I'm happy that the project is evolving, I started using it recently, and it helped me a lot with the implementation of using containers remotely where I can't expose the ports.
