### ISSUE TITLE
Impossible to log in with the new 0.9 version

### ISSUE THREAD

**Issue by soshimee** [playit-cloud/playit-agent#41]
There simply is no function to log in.

**Comment by loriopatrick** [comment]
Please provide more details

**Comment by giopalma** [comment]
There is no guide to explain how to log in.

For example [here](https://playit.gg/guides/minecraft-java/#true%2Ctrue%2Cfalse), if you follow this guide, you download playit as indicated and you click on "Downloaded", appears "Waiting for program to connect" but whay it's waiting? How to connect the program? There is no guide or tutorial. The software wants a secret code, where you can find it? Why don't write a tutorial to connect the agent with the website?

**Comment by maxomatic458** [comment]
@giopalma 
are you using version 0.9.3 ? [download](https://playit.gg/download)

that should automatically connect, you just need to start it up.
if your program requires a secret code, you might be using the new cli-version. there isnt any documentation for this version atm, so just use version 0.9.3

**Comment by loriopatrick** [comment]
I don't entirely follow, if someone things this needs a guide they can open an issue at https://github.com/playit-cloud/support-docs
