### ISSUE TITLE
I'm having a problem With playit.gg and my server 

### ISSUE THREAD

**Issue by ProMinerJon** [playit-cloud/playit-agent#46]
When I log onto my Server it fine for a bit until I get kick off Or timed out can't drop any item either.

Here is my latest log file ( Server side) 

[latest.log](https://github.com/playit-cloud/playit-agent/files/11974505/latest.log)

Client side latest log file 

[latest.log](https://github.com/playit-cloud/playit-agent/files/11974672/latest.log)

**Comment by loriopatrick** [comment]
Too general, might be resolved in latest release or with the ability to change routing
