### ISSUE TITLE
1.0.0rc5 closes shortly after opening on windows

### ISSUE THREAD

**Issue by maxomatic458** [playit-cloud/playit-agent#48]
this happens when opening via doubleclick or right click, open

when opening using an external cmd window it works

this line seems to panic 

https://github.com/playit-cloud/playit-agent/blob/ff6380d04ccc176048f96a22282c9d4ee4647907/packages/agent_cli/src/ui.rs#L23C1-L23C70

**Comment by loriopatrick** [comment]
On linux the purge only seems to reset the cursor position but not clear the text. I'll try to add some better error handling.

**Comment by maxomatic458** [comment]
this seems to work
```rs
let res: std::io::Result<()> = (|| {
    Clear(crossterm::terminal::ClearType::All).execute_winapi()?;
    stdout().execute(RestorePosition)?
        .execute(ResetColor)?
        .execute(Print(content_ref))?;

    Ok(())
})();
```
