### ISSUE TITLE
Agent Unassignable as Default on 0.13.0

### ISSUE THREAD

**Issue by CloudUltimat** [playit-cloud/playit-agent#55]
When trying to assign the updated client as a default agent, it will cause the exe to crash, nothing is reported about it failing in event viewer and there is no log/dmp to look at. This behavior **does not** happen when assigning it as non-default. Upon restarting client to see if it was successful in attempting to assign default the following is displayed:

![image](https://github.com/playit-cloud/playit-agent/assets/1341689/51241d3f-98b4-41c2-a236-777fa6a53550)

**Comment by loriopatrick** [comment]
Are you getting this issue in 0.14.0 or 0.15.0? I created a new backend API for the playit agent to use.

**Comment by loriopatrick** [comment]
Should be resolved, please open an new issue if you're still having issues.
