### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by froobieloo** [playit-cloud/playit-agent#56]
Error on download - unable to run '“playit” can’t be opened because Apple cannot check it for malicious software.'

**Comment by loriopatrick** [comment]
What version? We submit the program to be notarized by apple but it can take a few hours for them to authorize it sadly. I need to add an async task to our build pipeline that adds the notarization to the binary once apple has approved so you don't need public internet access to run the program without a warning.

**Comment by froobieloo** [comment]
Fixed - silly mistake being new to mac - opened by bypassing which I forgot you could do. Still learning how this machine works! Thanks for the quick response.
