### ISSUE TITLE
Status check or service check for tunnel functional.

### ISSUE THREAD

**Issue by kwslavens** [playit-cloud/playit-agent#57]
If possible can a tunnel status check be added? Something like 
  
  playit tunnel minecraft 
  
Returning a 1 for up or 0 for down? I'd like to eventually use this to setup a monitored cron script to restart the service if it goes down. 

If this is already possible can you point me in the right direction to find it?

**Comment by loriopatrick** [comment]
Out of scope for the client application. We did have a bug where playit would not reconnect properly, should be resolved now :crossed_fingers:. The playit backend may oneday offer monitoring and notifications if the origin for your tunnel goes down.
