### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by FamBoy32** [playit-cloud/playit-agent#67]
I had just switched from 0.9.3 to 0.15.10 and I ever since gotten API ERROR trying to connect to the agents. 
![Screenshot (7)](https://github.com/playit-cloud/playit-agent/assets/154202044/b4048920-06e2-4d3a-8927-011c861e6084)

**Comment by loriopatrick** [comment]
That's due to your account being over the agent limit. The error message now has more details but could still use some work.
