### ISSUE TITLE
internal exception 

### ISSUE THREAD

**Issue by Babygiryt** [playit-cloud/playit-agent#77]
: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: MAP_DATA, Type: OptionalComponentType, Index: 10, Data: [{VarInt: 1}, {ByteType: 1}, {BooleanType: true}, {VarInt: 2}], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$8 (Anonymous), Packet ID: 36
[07:35:54 INFO]: [AuctionHouse] Removing sell holding ins

**Comment by loriopatrick** [comment]
Appears to be an issue with your Minecraft server, not playit.gg. If you have mods / plugins they're likely causing the issue. If you're able to isolate the issue to playit please open a new issue with more details.
