### ISSUE TITLE
Excessive DNS requests

### ISSUE THREAD

**Issue by zakcodez** [playit-cloud/playit-agent#88]
I run playit.gg in a docker container which works fine, and I have a pi hole running on my network. For some reason, I found 28 thousand DNS requests to api.playit.gg over 5 hours. This calculated to approx 1.5 DNS requests per second! I haven't found any other problems, and my playit.gg version is 0.15.18. It's also getting the error "unexpected UDP establish packet" a lot.

**Comment by loriopatrick** [comment]
I’m not too concerned by the DNS lookup rate tho that could be optimized. The UDP error bug has been fixed in 0.15.19

**Comment by zakcodez** [comment]
The issue has been resolved in the latest version. Closing
