### ISSUE TITLE
Agent disconnecting at random

### ISSUE THREAD

**Issue by D1noD3v** [playit-cloud/playit-agent#90]
I run a machine with Ubuntu Server on it, on that server I also have a minecraft server running inside a docker container aswell as the playit-docker agent.

However at random times the agent will lose its connection to my server. I check the logs from the agent and nothing really seems like its out of the ordinary? It usually helps to restart the agent, after the restart it works fine. It's really annoying as I'm not always in near proximity to the server in order to restart the agent while other players want to play on the server.

I run the tunnel with global anycast and the default minecraft port configuration if that is of any help.

Has anyone else experienced the same error running a minecraft server? Any help is appriciated!

**Comment by loriopatrick** [comment]
There is currently no supported way to run the official playit docker image, it’s WIP. Is this something custom docker image you created? What version of the playit agent are you running?

**Comment by D1noD3v** [comment]
It seems I'm running the agent from a another repo. That repo is not associated with playit, my fault!

I'm gonna try to use the official application from playit.gg. The one i used is here: 
https://github.com/PepaonDrugs/playitgg-docker 
Might not be as stable though.
