### ISSUE TITLE
Adding Docker Links to Docs.

### ISSUE THREAD

**Issue by coloredbytes** [playit-cloud/playit-agent#91]
Would be nice to add a section under the docker part reading something like this.

## Docker

```
docker run --rm --net=host -e SECRET_KEY=<secret key> ghcr.io/playit-cloud/playit-agent:latest
```
> [!NOTE]
> Secret key can be generated [here](https://playit.gg/account/agents/new-docker).

**Comment by loriopatrick** [comment]
Good suggestion, thank you. I like the "Note" markdown :100:
